export const HOK_QUESTIONS = [
  {
    question: "Hoe diep moet je het borstbeen indrukken bij een volwassene tijdens reanimatie?",
    options: [
      "Minimaal 3 cm, maximaal 4 cm",
      "Minimaal 5 cm, maximaal 6 cm",
      "Minimaal 7 cm, maximaal 8 cm",
      "Minimaal 2 cm, maximaal 3 cm",
    ],
    correct_answer: 1,
    explanation: "Bij volwassenen druk je het borstbeen ten minste 5 cm maar niet meer dan 6 cm naar beneden.",
    time_limit: 20,
    video_topic: "Reanimatie: hoe diep druk je?",
    video_url: "",
  },
  {
    question: "Hoe snel geef je borstcompressies bij reanimatie?",
    options: [
      "60–80 per minuut",
      "80–100 per minuut",
      "100–120 per minuut",
      "120–140 per minuut",
    ],
    correct_answer: 2,
    explanation: "Het juiste tempo bij reanimatie is 100 tot 120 borstcompressies per minuut.",
    time_limit: 20,
    video_topic: "Reanimatie: het juiste tempo",
    video_url: "",
  },
  {
    question: "Wanneer leg je een bewusteloos slachtoffer NIET in de stabiele zijligging?",
    options: [
      "Als hij braakt",
      "Als er wervelletsel mogelijk is",
      "Als hij normaal ademt",
      "Als hij blauw ziet",
    ],
    correct_answer: 1,
    explanation: "Bij mogelijk wervelletsel (val van hoogte, auto-ongeluk) leg je het slachtoffer niet in de zijligging.",
    time_limit: 20,
    video_topic: "Stabiele zijligging — wanneer wel, wanneer niet?",
    video_url: "",
  },
  {
    question: "Hoe lang koel je een brandwond met lauw stromend kraanwater?",
    options: [
      "2–5 minuten",
      "10–20 minuten",
      "30–40 minuten",
      "1–2 minuten",
    ],
    correct_answer: 1,
    explanation: "Koel brandwonden 10–20 minuten met lauw zachtstromend kraanwater.",
    time_limit: 20,
    video_topic: "Brandwonden behandelen — koel & kalm",
    video_url: "",
  },
  {
    question: "Binnen hoeveel minuten na een circulatiestilstand moet een AED worden ingezet om de overlevingskans aanmerkelijk te vergroten?",
    options: [
      "2 minuten",
      "4 minuten",
      "6 minuten",
      "10 minuten",
    ],
    correct_answer: 2,
    explanation: "De inzet van een AED binnen 6 minuten vergroot aanmerkelijk de overlevingskans.",
    time_limit: 20,
    video_topic: "AED: elke seconde telt",
    video_url: "",
  },
  {
    question: "Iemand verslikt zich en kan niet meer praten. Wat doe je als eerste?",
    options: [
      "Direct buikstoten geven",
      "5 rugslagen geven",
      "Onmiddellijk 112 bellen",
      "De mond openen en kijken",
    ],
    correct_answer: 1,
    explanation: "Bij niet-effectief hoesten geef je eerst 5 rugslagen. Heeft dat geen effect? Dan geef je maximaal 5 buikstoten.",
    time_limit: 20,
    video_topic: "Verslikking — 5 rugslagen redden levens",
    video_url: "",
  },
  {
    question: "Hoe stel je vast of iemand bewusteloos is?",
    options: [
      "Kijk of de ogen open zijn",
      "Schud aan de schouders en spreek luid aan",
      "Controleer eerst de ademhaling",
      "Meet de polsslag",
    ],
    correct_answer: 1,
    explanation: "Iemand is bewusteloos als hij niet reageert op schudden aan de schouders en aanspreken.",
    time_limit: 20,
    video_topic: "Is iemand bewusteloos? Zo check je het",
    video_url: "",
  },
  {
    question: "Wat is de JUISTE verhouding borstcompressies en beademingen bij volwassenen?",
    options: [
      "15 : 2",
      "30 : 2",
      "30 : 5",
      "20 : 2",
    ],
    correct_answer: 1,
    explanation: "Bij reanimatie van volwassenen wissel je 30 borstcompressies af met 2 beademingen.",
    time_limit: 20,
    video_topic: "30:2 — de gouden reanimatieregel",
    video_url: "",
  },
  {
    question: "Welke test gebruik je om een beroerte te herkennen?",
    options: [
      "De ABCDE-methodiek",
      "De mond-spraak-arm test",
      "De pupilreflex test",
      "De bewustzijnstest",
    ],
    correct_answer: 1,
    explanation: "De mond-spraak-arm test: Mond (tanden laten zien), Spraak (een zin spreken), Arm (beide armen optillen).",
    time_limit: 20,
    video_topic: "Herken een beroerte in 3 stappen",
    video_url: "",
  },
  {
    question: "Iemand is bewusteloos met normale ademhaling. Wat doe je?",
    options: [
      "Direct reanimeren",
      "In de stabiele zijligging leggen",
      "Wachten tot hij bijkomt",
      "Alleen 112 bellen",
    ],
    correct_answer: 1,
    explanation: "Bewusteloos + normale ademhaling = stabiele zijligging. Zo blijft de luchtweg vrij en kan vocht uit de mond lopen.",
    time_limit: 20,
    video_topic: "Bewusteloos maar ademt — wat nu?",
    video_url: "",
  },
]
